#!/bin/sh
	
  echo ""
	echo "Assembling DSP code for a 4kx2k LBNL CCD"
	echo ""

# DOWNLOAD selects application code to be loaded from EEPROM or 
#   downloaded from the host over the fiber optic link

DOWNLOAD=HOST
WAVEFORM_FILE=$1
DST_FILE=$2

wine  /opt/CLAS563/BIN/asm56300 -b -ltim.ls -d DOWNLOAD $DOWNLOAD -d WAVEFORM_FILE "$WAVEFORM_FILE" tim.asm
wine  /opt/CLAS563/BIN/dsplnk -btim.cld -v tim.cln 
rm -f "$DST_FILE".lod
wine /opt/CLAS563/BIN/cldlod tim.cld > "$DST_FILE".lod
rm tim.cln ; rm tim.cld
dos2unix "$DST_FILE".lod


	echo ""
	echo "Created file $DST_FILE.lod for downloading over optical fiber"
	echo ""
